sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I0C2YQu18tNjgQkD5MwMbioSxiFHgv50sAsN+96NLxD7D3tReztoLsFzAhzdMF3AX+R9J68rEaCZ7pNjABgQr7kkmQGsJZpHZgnlp+xdWkHBL3Azu6FyVogRXWJzv6OjCGjlw3CxoTqh5irfX0/d3IC/X3zuSj9LSRlgKJBxKCbMxG0KdWz+C9mowyle9DhBaS+Sv/D1oM9TFxkHTizSwbveN6VC4iX7i0wmSujXy9XHcWIE51blTcegXEeDEdNtE3RRmycRIvrIvLL0oTK76AH2NxVlNtb05kW4823fisUvqpw/auqBulk128LSK9b6KKHS/oLAUnRvEgjJYQT/GZXkGiFYU17cue5DUb9iHKKsJTyThVGGPo2fkSlLnY60nlwNII8mjsbpGhERKCiLNQkiarQt/QOb4jxz7h4iSRzBdZ3Dh4E24ixeuIw2G1KzPzCH7EOKMFrDID/HXQKsipr8aD1VAtRE9q53BV3+5rduX0bEpYYjnjAFvZiIddAPWofM49P9CBoDKnMHxwW6/RdBeCpHHNmI3UJPAaVuqcdxbbMd1RzMCYxpab1qaiJyRwNKc/7bAV5Xzpv5xLx0khWcR0ERDEvOkStzzRwR2F9lIE0cs59Fl1cqnmb+eyXKpt6/QayLjjWhQSBuFR9+nRMbK+9t+DYP065YVPpiPCg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Zadig-ou-la-Destinee-histoire-orientale_4647
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy